### PR TITLE
Semantic ui

### PR DESCRIPTION
**Pull request by ofZach**
on this PR I will be migrating from bootstrap + select to semantic ui which is much cleaner / easier to style... 

screen shot 2015-08-25 at 5 53 11 am

### CODE REVIEW

**Comment by Daandelange** [comment]
If things break up I can have a look :)
(as JS and `class=""` and `id=""` are often related...)

**Comment by ofZach** [comment]
thanks!   this PR will be broken for a little while :)   just getting the scaffolding in now.  will ping when it's closer.

**Comment by ofZach** [comment]
it's going to take some time, just rebuilding the UI out first, then going to hook things up.   the multi-select is working now :)  

screen shot 2015-08-25 at 9 11 22 am

**Comment by ofZach** [comment]
advanced mode is now toggling platform selection...   

screen shot 2015-08-26 at 9 43 48 am
screen shot 2015-08-26 at 9 43 55 am
screen shot 2015-08-26 at 9 43 59 am

**Comment by ofZach** [comment]
also, I've removed the window chrome for now for a cooler look, just have to make the window draggable and add a close icon...  (and maybe some header / info)

**Comment by ofZach** [comment]
just a quick note that there is an error now with update multiple where it will generate a project on a folder that doesn't exist.  We should do some error checking against that path (the same way we error check the OF path) to make sure it exists and force people to use a real path there. 

we could alternatively make sure the command line tool errors out if it's recursive update flag is set and the path doesn't exist, but it seems good to stop it in the gui as well.

**Comment by ofZach** [comment]
we should check which templates exist to build our platform list.  if there's only one it could stay greyd out in advance as well.

**Pull request merged**
