### PR TITLE
More conventional electron structure

### PR DESCRIPTION
**Pull request by LeoColomb**
Build with [`generator-electron`](https://github.com/sindresorhus/generator-electron).

See the final structure: https://github.com/LeoColomb/pgElectron

### CODE REVIEW

**Comment by LeoColomb** [comment]
But :+1: for the project!

**Comment by ofZach** [comment]
yes!!!  thanks so much for the re-org, checking it out now...

**Comment by LeoColomb** [comment]
If you have any question, feel free, of course! :smile:

**Comment by Daandelange** [comment]
Thanks, looks good :)
But I fear a merge conflict with my new (local) commits, can I continue to push from #e085bbd ? (@ofZach)

**Comment by ofZach** [comment]
thanks !

**Comment by ofZach** [comment]
@LeoColomb when I build this on OSX, the distributions of windows and linux look a little bit wonky to me -- for example, the project generator app on windows is missing dlls when I copy it from the distribution folder -- here for example, I copied it to the desktop and tried to run it: 

screen shot 2015-08-19 at 10 52 49 am

is there a trick to this?   thanks!   (I don't seem to have the same problem if take the binary electron on windows and add the app by hand)

**Comment by LeoColomb** [comment]
Works well here. You need to keep the whole build folder, right?

---

image

---

Not sure to understand your situation... :innocent:

**Comment by LeoColomb** [comment]
> I copied it to the desktop

Ah.
Yes, you need the whole build folder.
See the [atom](http://atom.io) folder: 

---

image

**Comment by ofZach** [comment]
sorry I mistook how electron on windows works -- got it, it's all good.    

one q I had is is settings.json getting copied over?  I don't seem to see it in the dist examples: 

screen shot 2015-08-19 at 11 25 01 am

**Comment by ofZach** [comment]
also, I feel like we should leave the app uncompressed (no asar) so that folks can alter settings.json and how it works can be more clear...

I'll poke around the package.json and look at what some of what the packaging options do.

**Comment by LeoColomb** [comment]
`default_app` is not our app. That said I don't know what is it exactly for now, except a default electron app :smile: 

> settings.json getting copied over

In the asar archive.

> we should leave the app uncompressed (no asar) so that folks can alter settings.json

I don't see why exactly you prefer this (since source are dispo here) and settings is configurable in the app.

**Comment by ofZach** [comment]
about why having the file accessible, we may need to manually adjust settings for releases, for example, to make the IOS release, we need to change the default platform to ios.   also there may be settings (like show the dev tools) that make sense in the settings but aren't accessible to the end user.

**Comment by Daandelange** [comment]
Hey @LeoColomb , I just installed a node module (moniker) but `node_modules` is in the `.gitignore`.
How to add it as a dependency or how to ship the module within the repo ?

**Comment by Daandelange** [comment]
Oh wait, I got it, forgot the `--save` flag so it adds it as a dependency to `package.json` :)
So `npm install moniker --save` to install a new dependency.
Then when you download the repo, you have to `npm install` from the `app` dir. (@ofZach)
Sorry if it's obvious, I'm new to npm.

**Comment by LeoColomb** [comment]
> Sorry if it's obvious

:innocent: :kissing_heart:

**Pull request merged**
