### PR TITLE
Lint + manage settings.json

### PR DESCRIPTION
**Pull request by LeoColomb**
Default values for `settings.json`. 5ae592b946387c6214cba098fa819ccf73c91d72

### CODE REVIEW

**Comment by LeoColomb** [comment]
Oh and I add the icon. :tada:

**Comment by LeoColomb** [comment]
image

**Comment by ofZach** [comment]
thanks, but we need the menu to be able to copy & paste into fields...  (ie, without the menu, command-c and command-v don't work....)

**Comment by ofZach** [comment]
the other changes seem good !

**Comment by LeoColomb** [comment]
> we need the menu to be able to copy & paste into fields

Don't you prefer a context menu?
Let me tomorrow for a full review. :smiley:

**Comment by ofZach** [comment]
I don't know about context menus -- I just know that this is what I needed to get copy and paste work using command-c / command-v on osx in the text fields.

**Comment by Daandelange** [comment]
I merged it and restored the copy/paste menu. https://github.com/LeoColomb/pgElectron/commit/a7247ce704e6cba80af9a199cd063e2deb26d1bd
Thanks for you cleaning work @LeoColomb  :)

**Comment by LeoColomb** [comment]
OK, thanks! :smiley:

**Pull request merged**
